Repository heig-PDG/mono, pull requests merged in 2020-09, with the labels that each got.

#4 Write some documentation related to our workflow
  wiki/WORKFLOW.md
Labels: documentation

#10 Fix multiple typos
  .github/ISSUE_TEMPLATE/feature.md
  wiki/WORKFLOW.md
Labels: chore

#8 Fix #7
  wiki/WORKFLOW.md
Labels: documentation

#15 Add a branding document
  wiki/BRANDING.md
  wiki/assets/Fonts.png
Labels: documentation

#21 Update use cases
  wiki/SCENARIOS.md
Labels: documentation

#28 Define time tracking workflow
  wiki/TIMETRACKING.md
  wiki/assets/TimeTracking_EntryLate.png
  wiki/assets/TimeTracking_ManualEntry.png
  wiki/assets/TimeTracking_SelectProject.png
  wiki/assets/TimeTracking_SelectProjectTask.png
  wiki/assets/TimeTracking_StartTimer.png
Labels: documentation

#35 Fix building process
  website/package.json
Labels: bug

#36 Add a README.md file with references to our tools
  README.md
Labels: documentation

#45 Hotfix mobile version of website
  website/src/Main.elm
Labels: bug
