Repository heig-PDG/mono, pull requests merged in 2020-10, with the labels that each got.

#46 Add weekly timetracking
  .github/workflows/timetracking.yml
  TIMETRACKING.md
  timetracking/updateTimeTrack.py
Labels: documentation

#56 Update production assets
  website/static/assets/Four.png
  website/static/assets/One.png
  website/static/assets/Three.png
  website/static/assets/Two.png
Labels: chore

#57 Start setting the project up
  src/.gitignore
  src/build.gradle
  src/common/.gitignore
  src/common/build.gradle
  src/common/src/main/java/tupperdate/common/HelloWorld.kt
  src/gradle.properties
  src/gradle/wrapper/gradle-wrapper.jar
  src/gradle/wrapper/gradle-wrapper.properties
  src/gradlew
  src/gradlew.bat
  src/mobile/.gitignore
  src/mobile/build.gradle
  src/mobile/proguard-rules.pro
  src/mobile/src/androidTest/java/tupperdate/android/ExampleInstrumentedTest.kt
  src/mobile/src/main/AndroidManifest.xml
  src/mobile/src/main/java/tupperdate/android/MainActivity.kt
  src/mobile/src/main/res/drawable-v24/ic_launcher_foreground.xml
  src/mobile/src/main/res/drawable/ic_launcher_background.xml
  src/mobile/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  src/mobile/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  src/mobile/src/main/res/mipmap-hdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-hdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-mdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-mdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-xhdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-xxhdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  src/mobile/src/main/res/values/strings.xml
  src/mobile/src/main/res/values/themes.xml
  src/mobile/src/test/java/tupperdate/android/ExampleUnitTest.kt
  src/settings.gradle
  src/web/.gitignore
  src/web/build.gradle
  src/web/src/main/java/tupperdate/web/main.kt
Labels: platform-android, platform-backend, platform-common

#58 Set CI up
  .github/workflows/deploy.yml
  .github/workflows/timetracking.yml
  .github/workflows/web.yml
  README.md
  TIMETRACKING.md
  docker/build-image.sh
  docker/image/web/.gitignore
  docker/image/web/Dockerfile
  docker/publish-image-github.sh
  docker/publish-image-heroku.sh
  vcs/timetracking/updateTimeTrack.py
Labels: chore, documentation, platform-android, platform-backend, platform-common

#59 Set up Telegram messages on each backend deployment
  .github/workflows/web.yml
Labels: platform-backend

#60 Add a deployment script for the mobile app
  .github/workflows/android.yml
Labels: platform-android

#64 Add some branding (with a Jetpack Compose theme)
  src/mobile/src/main/java/tupperdate/android/MainActivity.kt
  src/mobile/src/main/java/tupperdate/android/ui/Branding.kt
  src/mobile/src/main/java/tupperdate/android/ui/Colors.kt
  src/mobile/src/main/java/tupperdate/android/ui/Themes.kt
  src/mobile/src/main/java/tupperdate/android/ui/Types.kt
  src/mobile/src/main/res/font/archivo_bold.ttf
  src/mobile/src/main/res/font/mulish_bold.ttf
  src/mobile/src/main/res/font/mulish_regular.ttf
  src/mobile/src/main/res/font/mulish_semibold.ttf
  src/mobile/src/main/res/values/themes.xml
Labels: platform-android

#66 Add a production app icon and fix activity alias
  src/mobile/src/main/AndroidManifest.xml
  src/mobile/src/main/ic_launcher-playstore.png
  src/mobile/src/main/res/drawable-v24/ic_launcher_foreground.xml
  src/mobile/src/main/res/drawable/ic_launcher_background.xml
  src/mobile/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  src/mobile/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  src/mobile/src/main/res/mipmap-hdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-hdpi/ic_launcher_background.png
  src/mobile/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  src/mobile/src/main/res/mipmap-hdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-mdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-mdpi/ic_launcher_background.png
  src/mobile/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  src/mobile/src/main/res/mipmap-mdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-xhdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  src/mobile/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  src/mobile/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-xxhdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  src/mobile/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  src/mobile/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  src/mobile/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  src/mobile/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  src/mobile/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  src/mobile/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: platform-android

#67 Add a GradientButton composable
  src/mobile/src/main/java/tupperdate/android/ui/Branding.kt
  src/mobile/src/main/java/tupperdate/android/ui/material/GradientButton.kt
Labels: chore, platform-android

#68 Fix README.md
  README.md
Labels: bug, chore

#71 Upgrade a few libraries
  src/build.gradle
  src/common/build.gradle
  src/mobile/build.gradle
Labels: chore

#78 Add formatted version name using last commit's date
  src/mobile/build.gradle
Labels: platform-android

#76 Add some real and mock Api files
  src/mobile/src/api/java/tupperdate/api/Api.kt
  src/mobile/src/api/java/tupperdate/api/RealApi.kt
  src/mobile/src/api/java/tupperdate/api/RealAuthenticationApi.kt
  src/mobile/src/api/java/tupperdate/api/RealRecipeApi.kt
  src/mobile/src/main/java/tupperdate/api/Activity.kt
  src/mobile/src/mock/java/tupperdate/api/Api.kt
  src/mobile/src/mock/java/tupperdate/api/MockApi.kt
  src/mobile/src/mock/java/tupperdate/api/MockAuthenticationApi.kt
  src/mobile/src/mock/java/tupperdate/api/MockRecipeApi.kt
Labels: platform-android

#80 Setup App structure
  src/mobile/src/main/java/tupperdate/android/App.kt
  src/mobile/src/main/java/tupperdate/android/MainActivity.kt
  src/mobile/src/main/java/tupperdate/android/NavGraph.kt
  src/mobile/src/main/java/tupperdate/android/home/Home.kt
  src/mobile/src/main/java/tupperdate/android/utils/Navigation.kt
Labels: platform-android

#83 Setup tests in CI
  .github/workflows/android-pr.yml
  .github/workflows/android.yml
  .github/workflows/deploy.yml
  .github/workflows/website.yml
  src/mobile/pr.jks
Labels: chore

#85 Add Kotlin styleguide for Android Studio
  vcs/codestyle/kotlin-intellij.xml
Labels: chore

#84 Onboarding screen
  src/mobile/src/main/java/tupperdate/android/App.kt
  src/mobile/src/main/java/tupperdate/android/NavGraph.kt
  src/mobile/src/main/java/tupperdate/android/appbars/mainBottomBar.kt
  src/mobile/src/main/java/tupperdate/android/appbars/mainTopBar.kt
  src/mobile/src/main/java/tupperdate/android/appbars/onlyReturnTopBar.kt
  src/mobile/src/main/java/tupperdate/android/home/Home.kt
  src/mobile/src/main/java/tupperdate/android/onboarding/BottomBar.kt
  src/mobile/src/main/java/tupperdate/android/onboarding/Onboarding.kt
  src/mobile/src/main/java/tupperdate/android/onboarding/OnboardingConfirmation.kt
  src/mobile/src/main/java/tupperdate/android/ui/Branding.kt
  src/mobile/src/main/java/tupperdate/android/ui/Themes.kt
  src/mobile/src/main/java/tupperdate/android/ui/material/BrandedButton.kt
  src/mobile/src/main/java/tupperdate/android/ui/material/BrandedTextField.kt
  src/mobile/src/main/java/tupperdate/android/utils/Navigation.kt
  src/mobile/src/main/res/drawable/ic_account_circle_black_18dp.xml
  src/mobile/src/main/res/drawable/ic_chat_24px.xml
  src/mobile/src/main/res/drawable/ic_clear_black_18dp.xml
  src/mobile/src/main/res/drawable/ic_fastfood_black_18dp.xml
  src/mobile/src/main/res/drawable/ic_favorite_border_black_18dp.xml
  src/mobile/src/main/res/drawable/ic_launcher_background.xml
  src/mobile/src/main/res/drawable/ic_navigate_before_black_18dp.xml
  src/mobile/src/main/res/values/onboarding.xml
Labels: platform-android

#92 Tweak a bit the UI of the onboarding screen
  src/mobile/src/main/java/tupperdate/android/onboarding/Onboarding.kt
  src/mobile/src/main/java/tupperdate/android/ui/material/BrandedTitleText.kt
  src/mobile/src/main/res/values/onboarding.xml
Labels: platform-android

#94 Deploy the wiki on dev pushes
  .github/workflows/wiki.yml
Labels: chore
