Repository heig-PDG/mono, pull requests merged in 2021-01, with the labels that each got.

#183 Add profile to Home
  src/mobile/src/main/java/tupperdate/android/data/legacy/RealApi.kt
  src/mobile/src/main/java/tupperdate/android/data/legacy/RealAuthenticationApi.kt
  src/mobile/src/main/java/tupperdate/android/data/legacy/RealUserApi.kt
  src/mobile/src/main/java/tupperdate/android/data/legacy/api/AuthenticationApi.kt
  src/mobile/src/main/java/tupperdate/android/data/legacy/api/UserApi.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/Home.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/profile/Profile.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileGeneral.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileSheet.kt
  src/mobile/src/main/java/tupperdate/android/ui/theme/Colors.kt
  src/mobile/src/main/java/tupperdate/android/ui/theme/modifier/MultiClick.kt
  src/mobile/src/main/res/drawable/ic_content_save.xml
  src/mobile/src/main/res/values/profile.xml
Labels: platform-android

#186 Add Chat API to spec
  spec/openapi.yaml
Labels: documentation

#187 Setup ktor unit testing with firebase emulators
  .github/scripts/emulator-env.sh
  .github/workflows/android-pr.yml
  .github/workflows/web-pr.yml
  src/web/build.gradle
  src/web/src/main/java/tupperdate/web/main.kt
  src/web/src/main/java/tupperdate/web/util/Config.kt
  src/web/src/test/java/tupperdate/web/simpleTest.kt
Labels: platform-backend

#192 Implement chat API endpoint to get all chats
  src/common/src/main/java/tupperdate/common/dto/ConversationDTO.kt
  src/common/src/main/java/tupperdate/common/dto/MessageContentDTO.kt
  src/common/src/main/java/tupperdate/common/dto/MessageDTO.kt
  src/common/src/main/java/tupperdate/common/dto/RecipeDTO.kt
  src/common/src/main/java/utils/TimestampSerializer.kt
  src/web/src/main/java/tupperdate/web/model/Chat.kt
  src/web/src/main/java/tupperdate/web/model/Recipe.kt
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.conversation.kt
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.get.kt
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.kt
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.messages.kt
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.post.kt
  src/web/src/main/java/tupperdate/web/routing/recipes/Recipes.like.kt
Labels: platform-backend

#195 Conversation endpoint
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.conversation.kt
  src/web/src/main/java/tupperdate/web/routing/chats/Chats.get.kt
Labels: platform-backend

#198 Improve profile API and token management
  src/mobile/build.gradle
  src/mobile/src/main/AndroidManifest.xml
  src/mobile/src/main/java/tupperdate/android/Tupperdate.kt
  src/mobile/src/main/java/tupperdate/android/data/Coroutines.kt
  src/mobile/src/main/java/tupperdate/android/data/Koin.kt
  src/mobile/src/main/java/tupperdate/android/data/Uris.kt
  src/mobile/src/main/java/tupperdate/android/data/Work.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/AuthenticationStatus.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/Koin.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/firebase/Coroutines.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/firebase/FirebaseAuthProvider.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/firebase/FirebaseAuthenticationRepository.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/firebase/FirebasePhoneRegistration.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/firebase/FirebaseUid.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/impl/FirebaseAuthenticationRepository.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/room/Entity.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/room/ProfileDao.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/store/ProfileFetcher.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/store/ProfileSourceOfTruth.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/work/RefreshProfileWorker.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/work/UpdateProfileWorker.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/README.md
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/RecipeRepository.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/impl/RecipeRepositoryImpl.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/room/Dto.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/room/Entity.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/room/RecipeDao.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/room/RecipeEntity.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/room/RecipeSourceOfTruth.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/room/RecipeStackSourceOfTruth.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/work/NewRecipeWorker.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/work/RefreshStackWorker.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/work/SyncPendingCreationsWorker.kt
  src/mobile/src/main/java/tupperdate/android/data/features/recipe/work/SyncPendingVotesWorker.kt
  src/mobile/src/main/java/tupperdate/android/data/room/TupperdateDatabase.kt
  src/mobile/src/main/java/tupperdate/android/ui/App.kt
  src/mobile/src/main/java/tupperdate/android/ui/MainActivity.kt
  src/mobile/src/main/java/tupperdate/android/ui/ambients/Api.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/Koin.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/feed/Feed.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/feed/FeedViewModel.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/profile/Profile.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/profile/ProfileSheet.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/recipe/NewRecipe.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/recipe/NewRecipeViewModel.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/recipe/ViewRecipe.kt
  src/mobile/src/main/java/tupperdate/android/ui/onboarding/Koin.kt
  src/mobile/src/main/java/tupperdate/android/ui/onboarding/OnboardingProfile.kt
  src/mobile/src/main/java/tupperdate/android/ui/onboarding/OnboardingProfile.stateful.kt
  src/mobile/src/main/java/tupperdate/android/ui/onboarding/OnboardingProfileViewModel.kt
  src/mobile/src/test/java/tupperdate/android/data/CoroutinesTest.kt
  src/web/src/main/java/tupperdate/web/routing/recipes/Recipes.get.kt
Labels: platform-android, platform-backend

#209 Add user phone to UserDTO
  src/common/src/main/java/tupperdate/common/dto/UserDTO.kt
  src/web/src/main/java/tupperdate/web/main.kt
  src/web/src/main/java/tupperdate/web/model/User.kt
  src/web/src/main/java/tupperdate/web/routing/users/Users.get.kt
  src/web/src/main/java/tupperdate/web/routing/users/Users.kt
Labels: bug

#217 Fix server
  src/web/src/main/java/tupperdate/web/routing/recipes/Recipes.get.kt
Labels: bug

#232 Add FCM support
  src/common/src/main/java/tupperdate/common/dto/NewNotificationTokenDTO.kt
  src/common/src/main/java/tupperdate/common/dto/notifications/Types.kt
  src/mobile/build.gradle
  src/mobile/src/main/AndroidManifest.xml
  src/mobile/src/main/java/tupperdate/android/Tupperdate.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/Koin.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/Notification.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/NotificationRepository.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/NotificationToken.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/impl/NotificationRepositoryImpl.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/impl/RemoteMessage.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/impl/TupperdateNotificationService.kt
  src/mobile/src/main/java/tupperdate/android/data/features/notifications/work/LinkWorker.kt
  src/web/src/main/java/tupperdate/web/Controller.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/Koin.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/NewNotificationToken.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/ProfileFacade.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/ProfileFacadeImpl.kt
  src/web/src/main/java/tupperdate/web/main.kt
  src/web/src/main/java/tupperdate/web/model/accounts/Notification.kt
  src/web/src/main/java/tupperdate/web/model/accounts/NotificationRepository.kt
  src/web/src/main/java/tupperdate/web/model/accounts/fcm/FcmNotificationRepository.kt
  src/web/src/main/java/tupperdate/web/model/accounts/fcm/Koin.kt
  src/web/src/main/java/tupperdate/web/model/accounts/fcm/Notifications.kt
  src/web/src/main/java/tupperdate/web/model/impl/firestore/Koin.kt
  src/web/src/main/java/tupperdate/web/model/profiles/ModelNotificationToken.kt
  src/web/src/main/java/tupperdate/web/model/profiles/UserRepository.kt
  src/web/src/main/java/tupperdate/web/model/profiles/firestore/FirestoreUserRepository.kt
  src/web/src/test/java/tupperdate/web/koin/Koin.kt
  src/web/src/test/java/tupperdate/web/koin/NotificationRepositoryMock.kt
  src/web/src/test/java/tupperdate/web/koin/Setup.kt
Labels: platform-android, platform-backend, platform-common

#234 Add empty chat screen and fix onboarding
  src/mobile/src/main/java/tupperdate/android/ui/home/chats/Conversations.stateful.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/chats/EmptyConversations.kt
  src/mobile/src/main/res/drawable/empty_chat_screen.xml
  src/mobile/src/main/res/values/chat.xml
  src/web/src/main/java/tupperdate/web/model/profiles/firestore/FirestoreUser.kt
  src/web/src/main/java/tupperdate/web/model/profiles/firestore/FirestoreUserRepository.kt
Labels: bug

#242 Add a swipe overlay to recipes in the stack
  src/mobile/src/main/java/tupperdate/android/ui/home/feed/Feed.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/feed/RecipeCard.kt
  src/mobile/src/main/java/tupperdate/android/ui/home/feed/SwipeOverlay.kt
Labels: platform-android

#245 Add user profile PATCH
  src/common/src/main/java/tupperdate/common/dto/MyUserPartDTO.kt
  src/common/src/main/java/utils/OptionalProperty.kt
  src/mobile/src/main/java/tupperdate/android/data/Koin.kt
  src/mobile/src/main/java/tupperdate/android/data/features/auth/work/UpdateProfileWorker.kt
  src/web/src/main/java/tupperdate/web/Controller.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/PartProfile.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/ProfileFacade.kt
  src/web/src/main/java/tupperdate/web/facade/profiles/ProfileFacadeImpl.kt
  src/web/src/main/java/tupperdate/web/main.kt
  src/web/src/main/java/tupperdate/web/model/profiles/ModelPartUser.kt
  src/web/src/main/java/tupperdate/web/model/profiles/UserRepository.kt
  src/web/src/main/java/tupperdate/web/model/profiles/firestore/FirestoreUserRepository.kt
  src/web/src/test/java/tupperdate/web/users.kt
Labels: platform-android, platform-backend
